version: '3'

services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "15432:5432"
    volumes:
      - /home/pedro/Documentos/projetos/api-adega/adegaApp/data:/var/lib/postgresql/data
